import dspy

class AgentResponseSignature(dspy.Signature):
    """Refine the message to a friendly tone"""
    user_input = dspy.InputField(desc="The user's original query or statement.")
    agent_answer = dspy.InputField(desc="The direct answer generated by the agent.")
    agent_reasoning = dspy.InputField(desc="The thought process that led to the agent's answer.")

    message: str = dspy.OutputField(desc="A refined message with a friendly tone, appropriate language, and emojis, based on the agent's answer and reasoning.")
